export const classes = [
    {
        "courseCode": "EL2001",
        "courseName": "Smart Grid And Technologies",
        "courseType": "Lecture",
        "year": "4th",
        "semester": "8th",
        "department": "EE",
        "electiveType": "DEC1", // DEC1/OE2
        "batch": "G1",
        "teacherName": "Balwinder Singh",
        "day": "Monday",
        "timeSlot": "8-9",
        "roomName": "L-5",
    },
    {
        "courseCode": "CSE6002",
        "courseName": "Operating System",
        "courseType": "Lecture",
        "year": "4th",
        "semester": "6th",
        "department": "CSE",
        "electiveType": "OE1", // DEC1/OE2
        "batch": "G1",
        "teacherName": "Amandeep Kaur",
        "day": "Monday",
        "timeSlot": "8-9",
        "roomName": "L-20",
    },
    {
        "courseCode": "EL2002",
        "courseName": "Power System",
        "courseType": "Tutorial",
        "year": "4th",
        "semester": "8th",
        "department": "EE",
        "electiveType": "DEC1", // DEC1/OE2
        "batch": "G1",
        "teacherName": "Balwinder Singh",
        "day": "Wednesday",
        "timeSlot": "9-10",
        "roomName": "L-5",
    },
    {
        "courseCode": "EL2003",
        "courseName": "Renewable",
        "courseType": "Lecture",
        "year": "4th",
        "semester": "8th",
        "department": "EE",
        "electiveType": "DEC1", // DEC1/OE2
        "batch": "G1",
        "teacherName": "Nandika Kaur",
        "day": "Wednesday",
        "timeSlot": "9-10",
        "roomName": "L-5",
    },
    {
        "courseCode": "EL2004",
        "courseName": "Electrical Machines",
        "courseType": "Practical",
        "year": "3rd",
        "semester": "8th",
        "department": "EE",
        "electiveType": "DEC1", // DEC1/OE2
        "batch": "G1",
        "teacherName": "Dhiraj Bharat",
        "day": "Friday",
        "timeSlot": "8-10",
        "roomName": "Machines Lab",
    },
    {
        "courseCode": "EL2004",
        "courseName": "Electrical Machines",
        "courseType": "Practical",
        "year": "3rd",
        "semester": "8th",
        "department": "EE",
        "electiveType": "DEC1", // DEC1/OE2
        "batch": "G1",
        "teacherName": "Dhiraj Bharat",
        "day": "Friday",
        "timeSlot": "13-15",
        "roomName": "Machines Lab",
    },
]


